### PR TITLE
#11 this corrects the boundary information being included in the cont…

### PR DESCRIPTION
**Pull request by tony-o**
…ent type validation

### CODE REVIEW

**Comment by tony-o** [comment]
@jnthn my man, how do I get this merged?

**Comment by jnthn** [comment]
Ah, sorry. The test failures concerned me, then I forgot to look into it (or ask a colleague to do so). I've run the couple that failed again to see if it was something temporarily broken in a dependency.

**Comment by tony-o** [comment]
@jnthn i suspect the regression is elsewhere, i was attempting to debug and learned:

```
λ ~/projects/perl6/cro-openapi-routes-from-definition$ perl6 -Ilib t/basic-operations.t
^C
λ ~/projects/perl6/cro-openapi-routes-from-definition$ perl6 -v
This is Rakudo version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.
λ ~/projects/perl6/cro-openapi-routes-from-definition$ perl6 -Ilib t/basic-operations.t
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse)
    ok 3 - .what matches get
ok 1 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse?
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse)
    ok 3 - .what matches post
ok 2 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse?
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse)
    ok 3 - .what matches include
ok 3 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse?
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse)
    ok 3 - .what matches delegate
ok 4 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::InvalidUse?
ok 5 - With :ignore-unimplemented, no error even if no operations implemented
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::UnimplementedOperations)
    ok 3 - .operations matches [createPets listPets showPetById]
ok 6 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::UnimplementedOperations?
ok 7 - Valid opperation declarations are accepted
    1..3
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::UnspecifiedOperation)
    ok 3 - .operation matches surprise
ok 8 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::UnspecifiedOperation?
    1..6
    ok 1 - code dies
    ok 2 - right exception type (X::Cro::OpenAPI::RoutesFromDefinition::WrongPathSegmentCount)
    ok 3 - .operation matches showPetById
    ok 4 - .path-template matches /pets/{petId}
    ok 5 - .got matches 0
    ok 6 - .expected matches 1
ok 9 - did we throws-like X::Cro::OpenAPI::RoutesFromDefinition::WrongPathSegmentCount?
    not ok 1 - Can call listPets operation
    # Failed test 'Can call listPets operation'
    # at t/basic-operations.t line 325
    # expected: ${:code(42), :message("listPets NYI")}
    #      got: "WRONG"
    ok 2 - Can call createPets operation
    not ok 3 - Can call showPetById operation
    # Failed test 'Can call showPetById operation'
    # at t/basic-operations.t line 331
    # expected: ${:code(42), :message("showPetById(101) NYI")}
    #      got: "WRONG"
    1..3
    # Looks like you failed 2 tests of 3
not ok 10 - Basic operation handler invocation
# Failed test 'Basic operation handler invocation'
# at t/basic-operations.t line 288
1..10
# Looks like you failed 1 test of 10
λ ~/projects/perl6/cro-openapi-routes-from-definition$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
λ ~/projects/perl6/cro-openapi-routes-from-definition$ git pull
Already up to date.```

Running a bisect and will post here ..

**Comment by tony-o** [comment]
```
λ ~/projects/perl6/cro-openapi-routes-from-definition$ git bisect log
git bisect start
# good: [a85740c0d766a17e88a6f149be9b2f15ab8ebca4] First pass at describing this module
git bisect good a85740c0d766a17e88a6f149be9b2f15ab8ebca4
# bad: [b0a660b7496cca64990e1d492b5333c280ea40fe] Add more travis targets
git bisect bad b0a660b7496cca64990e1d492b5333c280ea40fe
# bad: [4239d0ca9a0f7b00787801c8cb6fd2a0a1a90816] Implement :!response-validation option
git bisect bad 4239d0ca9a0f7b00787801c8cb6fd2a0a1a90816
# bad: [ba9944478ae5837dd6d8a41e90f8f90e936c7cd6] Check validating body doesn't lose it
git bisect bad ba9944478ae5837dd6d8a41e90f8f90e936c7cd6
# bad: [256389c5adc4cb67a875512974c9334d9149ea8a] Depend on OpenAPI::Schema::Validate
git bisect bad 256389c5adc4cb67a875512974c9334d9149ea8a
# bad: [f0b03e55edcc91cafc46330dc7b7b57cf0ee29d7] Try to parse the OpenAPI model
git bisect bad f0b03e55edcc91cafc46330dc7b7b57cf0ee29d7
# bad: [2eb34b68558e0d45db0ae6447734e3042ce26b6c] Stub the module
git bisect bad 2eb34b68558e0d45db0ae6447734e3042ce26b6c
# first bad commit: [2eb34b68558e0d45db0ae6447734e3042ce26b6c] Stub the module
```

Which makes me think it's a problem with 2019.03 rather than this module or PR.

**Comment by tony-o** [comment]
Any chance on getting the merge?

**Comment by jnthn** [comment]
I just came to report this bug and stumbled upon the PR. Sorry! I agree it's probably due to the something with 2019.03.

**Pull request merged**
